# Generated by Django 5.2.1 on 2025-05-31 10:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dht11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField(verbose_name='humidity')),
                ('temperature', models.FloatField(verbose_name='temperature')),
            ],
        ),
        migrations.CreateModel(
            name='ens160',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvoc', models.FloatField(verbose_name='tvoc')),
                ('eco2', models.FloatField(verbose_name='eco2')),
                ('aqi', models.FloatField(verbose_name='aqi')),
            ],
        ),
        migrations.CreateModel(
            name='gy906',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='temperature')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, verbose_name='Room number')),
                ('floor', models.IntegerField(verbose_name='Floor')),
                ('capacity', models.IntegerField(verbose_name='Max People Inside')),
                ('description', models.CharField(max_length=100, verbose_name='Description of Room')),
            ],
        ),
        migrations.CreateModel(
            name='sen22396',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.FloatField(verbose_name='co2')),
                ('humidity', models.FloatField(verbose_name='humidity')),
                ('temperature', models.FloatField(verbose_name='temperature')),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_read_access', models.BooleanField(default=False)),
                ('has_read_write_access', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye_app.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('temperature_ambient', 'Temperatura (otoczenie)'), ('temperature_close', 'Temperatura (zbliżeniowa)'), ('humidity', 'Wilgotność'), ('co2', 'CO₂'), ('tvoc', 'TVOC'), ('eco2', 'eCO₂'), ('aqi', 'Jakość powietrza (AQI)')], default='default./', max_length=50)),
                ('custom_name', models.CharField(blank=True, max_length=100)),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('url', models.URLField()),
                ('port', models.PositiveIntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye_app.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomQualities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_bad_temp_otocz', models.FloatField(default=0.0)),
                ('min_mid_temp_otocz', models.FloatField(default=0.0)),
                ('max_mid_temp_otocz', models.FloatField(default=0.0)),
                ('min_good_temp_otocz', models.FloatField(default=0.0)),
                ('max_good_temp_otocz', models.FloatField(default=0.0)),
                ('min_mid2_temp_otocz', models.FloatField(default=0.0)),
                ('max_mid2_temp_otocz', models.FloatField(default=0.0)),
                ('min_bad2_temp_otocz', models.FloatField(default=0.0)),
                ('max_bad_temp_zbliz', models.FloatField(default=0.0)),
                ('min_mid_temp_zbliz', models.FloatField(default=0.0)),
                ('max_mid_temp_zbliz', models.FloatField(default=0.0)),
                ('min_good_temp_zbliz', models.FloatField(default=0.0)),
                ('max_good_temp_zbliz', models.FloatField(default=0.0)),
                ('min_mid2_temp_zbliz', models.FloatField(default=0.0)),
                ('max_mid2_temp_zbliz', models.FloatField(default=0.0)),
                ('min_bad2_temp_zbliz', models.FloatField(default=0.0)),
                ('max_bad_wiglotnosc', models.FloatField(default=0.0)),
                ('min_mid_wiglotnosc', models.FloatField(default=0.0)),
                ('max_mid_wiglotnosc', models.FloatField(default=0.0)),
                ('min_good_wiglotnosc', models.FloatField(default=0.0)),
                ('max_good_wiglotnosc', models.FloatField(default=0.0)),
                ('min_mid2_wiglotnosc', models.FloatField(default=0.0)),
                ('max_mid2_wiglotnosc', models.FloatField(default=0.0)),
                ('min_bad2_wiglotnosc', models.FloatField(default=0.0)),
                ('max_good_co2', models.FloatField(default=0.0)),
                ('min_mid_co2', models.FloatField(default=0.0)),
                ('max_mid_co2', models.FloatField(default=0.0)),
                ('min_bad_co2', models.FloatField(default=0.0)),
                ('max_good_tvoc', models.FloatField(default=0.0)),
                ('min_mid_tvoc', models.FloatField(default=0.0)),
                ('max_mid_tvoc', models.FloatField(default=0.0)),
                ('min_bad_tvoc', models.FloatField(default=0.0)),
                ('max_good_eco2', models.FloatField(default=0.0)),
                ('min_mid_eco2', models.FloatField(default=0.0)),
                ('max_mid_eco2', models.FloatField(default=0.0)),
                ('min_bad_eco2', models.FloatField(default=0.0)),
                ('max_good_aqi', models.FloatField(default=0.0)),
                ('min_mid_aqi', models.FloatField(default=0.0)),
                ('max_mid_aqi', models.FloatField(default=0.0)),
                ('min_bad_aqi', models.FloatField(default=0.0)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality', to='eye_app.room')),
            ],
        ),
        migrations.CreateModel(
            name='SensorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.CharField(max_length=64, unique=True)),
                ('ip', models.CharField(default='0.0.0.0', max_length=50, unique=True)),
                ('key', models.CharField(max_length=64)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eye_app.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='device_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Device_ID', to='eye_app.sensordevice'),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('dht11', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eye_app.dht11')),
                ('ens160', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eye_app.ens160')),
                ('gy906', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eye_app.gy906')),
                ('sen22396', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eye_app.sen22396')),
                ('dev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dev_ID', to='eye_app.sensordevice')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('visible', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye_app.room')),
            ],
            options={
                'unique_together': {('room', 'parameter')},
            },
        ),
        migrations.CreateModel(
            name='ParameterRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity')], max_length=20)),
                ('quality', models.CharField(choices=[('bad', 'Zły'), ('medium', 'Średni'), ('good', 'Dobry')], max_length=10)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye_app.room')),
            ],
            options={
                'unique_together': {('room', 'parameter', 'quality')},
            },
        ),
    ]
