# Generated by Django 5.2.1 on 2025-05-31 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye_app', '0002_alter_measurement_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomactions',
            name='port',
        ),
    ]
