# Generated by Django 5.2.1 on 2025-11-16 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('ip_address', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('installed_date', models.DateField()),
                ('last_seen', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('enable_alerts', models.BooleanField()),
                ('enable_monthly_energy_consumption_limit', models.BooleanField()),
                ('monthly_energy_consumption_limit', models.FloatField()),
                ('enable_current_limit', models.BooleanField()),
                ('current_limit_per_phase', models.FloatField()),
                ('enable_active_power_limit', models.BooleanField()),
                ('active_power_limit_per_phase', models.FloatField()),
                ('enable_apparent_power_limit', models.BooleanField()),
                ('apparent_power_limit_per_phase', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('floor', models.IntegerField()),
                ('number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='RoomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SwitchBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=16)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slave_id', models.IntegerField(default=-1)),
                ('model', models.CharField(max_length=32)),
                ('three_phases', models.BooleanField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.channel')),
                ('limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.limit')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingOnePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_time', models.DateTimeField()),
                ('total_active_energy', models.FloatField()),
                ('total_reactive_energy', models.FloatField()),
                ('total_active_power', models.FloatField()),
                ('total_reactive_power', models.FloatField()),
                ('total_apparent_power', models.FloatField()),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('frequency', models.FloatField()),
                ('electric_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.electricmeter')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingThreePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_time', models.DateTimeField()),
                ('total_active_energy', models.FloatField()),
                ('L1_active_energy', models.FloatField()),
                ('L2_active_energy', models.FloatField()),
                ('L3_active_energy', models.FloatField()),
                ('total_reactive_energy', models.FloatField()),
                ('L1_reactive_energy', models.FloatField()),
                ('L2_reactive_energy', models.FloatField()),
                ('L3_reactive_energy', models.FloatField()),
                ('total_active_power', models.FloatField()),
                ('L1_active_power', models.FloatField()),
                ('L2_active_power', models.FloatField()),
                ('L3_active_power', models.FloatField()),
                ('total_reactive_power', models.FloatField()),
                ('L1_reactive_power', models.FloatField()),
                ('L2_reactive_power', models.FloatField()),
                ('L3_reactive_power', models.FloatField()),
                ('total_apparent_power', models.FloatField()),
                ('L1_apparent_power', models.FloatField()),
                ('L2_apparent_power', models.FloatField()),
                ('L3_apparent_power', models.FloatField()),
                ('L1_voltage', models.FloatField()),
                ('L2_voltage', models.FloatField()),
                ('L3_voltage', models.FloatField()),
                ('L1_current', models.FloatField()),
                ('L2_current', models.FloatField()),
                ('L3_current', models.FloatField()),
                ('frequency', models.FloatField()),
                ('electric_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.electricmeter')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.roomgroup'),
        ),
        migrations.AddField(
            model_name='device',
            name='switch_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.switchboard'),
        ),
    ]
