# Generated by Django 5.2.1 on 2025-11-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricmeter',
            name='slave_id',
            field=models.IntegerField(),
        ),
    ]
