# Generated by Django 5.2.1 on 2025-11-16 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_electricmeter_slave_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricmeter',
            name='limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.limit'),
        ),
        migrations.AlterField(
            model_name='electricmeter',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.room'),
        ),
    ]
