# Generated by Django 5.2.8 on 2025-11-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_alter_electricmeter_limit_alter_electricmeter_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='devices', to='auth.group', verbose_name='device_groups'),
        ),
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='device',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='device',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='device_set', to='auth.permission', verbose_name='device_permissions'),
        ),
    ]
