# Generated by Django 5.2.8 on 2025-11-24 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_device_groups_device_is_active_device_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricmeter',
            name='room',
        ),
        migrations.AddField(
            model_name='electricmeter',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.device'),
        ),
    ]
