# Generated by Django 5.2.8 on 2025-12-05 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userrole_chat_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.roomgroup'),
        ),
    ]
