# Generated by Django 5.2.8 on 2025-12-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chat_assigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(default='Zgłoszenie', max_length=64),
        ),
    ]
