# Generated by Django 5.2.8 on 2025-12-06 19:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_chat_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_msg_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
