# Generated by Django 5.2.8 on 2025-12-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_chat_last_msg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='baud_rate',
            field=models.IntegerField(default=9600),
        ),
        migrations.AddField(
            model_name='channel',
            name='data_len',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='channel',
            name='parity',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='channel',
            name='stop_bits',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='channel',
            name='uart',
            field=models.CharField(default='/dev/null', max_length=16),
        ),
        migrations.AddField(
            model_name='device',
            name='flushing_interval',
            field=models.IntegerField(default=1800),
        ),
        migrations.AddField(
            model_name='device',
            name='last_edit_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='polling_interval',
            field=models.IntegerField(default=1800),
        ),
    ]
