# Generated by Django 5.2.8 on 2025-12-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_channel_channel_name_alter_device_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='end_lease_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='start_lease_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
