# Generated by Django 5.2.8 on 2025-12-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_room_end_lease_date_room_start_lease_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
    ]
