# Generated by Django 5.2.8 on 2025-12-20 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_room_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricmeter',
            name='device',
        ),
        migrations.RemoveField(
            model_name='electricmeter',
            name='limit',
        ),
        migrations.AddField(
            model_name='limit',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.electricmeter'),
        ),
    ]
