# Generated by Django 5.2.8 on 2025-12-20 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_electricmeter_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricmeter',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.room'),
        ),
    ]
