# Generated by Django 5.2.8 on 2025-12-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_electricmeter_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricmeter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
