# Generated by Django 5.2.8 on 2025-12-20 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_electricmeter_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingthreephase',
            name='electric_meter',
        ),
        migrations.RemoveField(
            model_name='limit',
            name='active_power_limit_per_phase',
        ),
        migrations.RemoveField(
            model_name='limit',
            name='apparent_power_limit_per_phase',
        ),
        migrations.RemoveField(
            model_name='limit',
            name='current_limit_per_phase',
        ),
        migrations.RemoveField(
            model_name='limit',
            name='enable_active_power_limit',
        ),
        migrations.RemoveField(
            model_name='limit',
            name='enable_apparent_power_limit',
        ),
        migrations.RemoveField(
            model_name='limit',
            name='enable_current_limit',
        ),
        migrations.RemoveField(
            model_name='limit',
            name='enable_monthly_energy_consumption_limit',
        ),
        migrations.RemoveField(
            model_name='limit',
            name='monthly_energy_consumption_limit',
        ),
        migrations.AddField(
            model_name='limit',
            name='l1_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='limit',
            name='l2_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='limit',
            name='l3_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='limit',
            name='max_active_power',
            field=models.IntegerField(default=18400),
        ),
        migrations.AddField(
            model_name='limit',
            name='max_current',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='limit',
            name='max_frequency',
            field=models.FloatField(default=50.5),
        ),
        migrations.AddField(
            model_name='limit',
            name='max_power_factor',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='limit',
            name='max_reactive_power',
            field=models.IntegerField(default=18400),
        ),
        migrations.AddField(
            model_name='limit',
            name='max_voltage',
            field=models.IntegerField(default=253),
        ),
        migrations.AddField(
            model_name='limit',
            name='min_active_power',
            field=models.IntegerField(default=-18400),
        ),
        migrations.AddField(
            model_name='limit',
            name='min_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='limit',
            name='min_frequency',
            field=models.FloatField(default=49.5),
        ),
        migrations.AddField(
            model_name='limit',
            name='min_power_factor',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='limit',
            name='min_reactive_power',
            field=models.IntegerField(default=-18400),
        ),
        migrations.AddField(
            model_name='limit',
            name='min_voltage',
            field=models.IntegerField(default=207),
        ),
        migrations.AddField(
            model_name='limit',
            name='monitor_active_power',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='limit',
            name='monitor_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='limit',
            name='monitor_frequency',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='limit',
            name='monitor_power_factor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='limit',
            name='monitor_reactive_power',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='limit',
            name='monitor_voltage',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_time', models.DateTimeField()),
                ('total_active_energy', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_reactive_energy', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frequency', models.FloatField()),
                ('l1_voltage', models.FloatField(default=0)),
                ('l2_voltage', models.FloatField(blank=True, null=True)),
                ('l3_voltage', models.FloatField(blank=True, null=True)),
                ('l1_current', models.FloatField(default=0)),
                ('l2_current', models.FloatField(blank=True, null=True)),
                ('l3_current', models.FloatField(blank=True, null=True)),
                ('total_active_power', models.FloatField(default=0)),
                ('l1_active_power', models.FloatField(default=0)),
                ('l2_active_power', models.FloatField(blank=True, null=True)),
                ('l3_active_power', models.FloatField(blank=True, null=True)),
                ('total_reactive_power', models.FloatField(default=0)),
                ('l1_reactive_power', models.FloatField(default=0)),
                ('l2_reactive_power', models.FloatField(blank=True, null=True)),
                ('l3_reactive_power', models.FloatField(blank=True, null=True)),
                ('total_apparent_power', models.FloatField(default=0)),
                ('total_power_factor', models.FloatField(default=0)),
                ('l1_power_factor', models.FloatField(default=0)),
                ('l2_power_factor', models.FloatField(blank=True, null=True)),
                ('l3_power_factor', models.FloatField(blank=True, null=True)),
                ('electric_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.electricmeter')),
            ],
            options={
                'ordering': ['-reading_time'],
            },
        ),
        migrations.DeleteModel(
            name='ReadingOnePhase',
        ),
        migrations.DeleteModel(
            name='ReadingThreePhase',
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['electric_meter', 'reading_time'], name='core_meterr_electri_08dd2d_idx'),
        ),
    ]
