# Generated by Django 5.2.8 on 2025-12-20 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_readingthreephase_electric_meter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('enable_alerts', models.BooleanField()),
                ('monitor_voltage', models.BooleanField(default=True)),
                ('monitor_current', models.BooleanField(default=True)),
                ('monitor_frequency', models.BooleanField(default=True)),
                ('monitor_active_power', models.BooleanField(default=True)),
                ('monitor_reactive_power', models.BooleanField(default=True)),
                ('monitor_power_factor', models.BooleanField(default=True)),
                ('l1_enable', models.BooleanField(default=True)),
                ('l2_enable', models.BooleanField(default=True)),
                ('l3_enable', models.BooleanField(default=True)),
                ('min_voltage', models.IntegerField(default=207)),
                ('max_voltage', models.IntegerField(default=253)),
                ('min_frequency', models.FloatField(default=49.5)),
                ('max_frequency', models.FloatField(default=50.5)),
                ('min_current', models.IntegerField(default=0)),
                ('max_current', models.IntegerField(default=80)),
                ('min_active_power', models.IntegerField(default=-18400)),
                ('max_active_power', models.IntegerField(default=18400)),
                ('min_reactive_power', models.IntegerField(default=-18400)),
                ('max_reactive_power', models.IntegerField(default=18400)),
                ('min_power_factor', models.FloatField(default=0.2)),
                ('max_power_factor', models.FloatField(default=1.0)),
            ],
        ),
        migrations.AddField(
            model_name='electricmeter',
            name='alert_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.alertprofile'),
        ),
        migrations.DeleteModel(
            name='Limit',
        ),
    ]
