# Generated by Django 5.2.8 on 2025-12-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alertprofile_electricmeter_alert_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertprofile',
            old_name='enable_alerts',
            new_name='is_active',
        ),
    ]
