# Generated by Django 5.2.8 on 2025-12-28 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_enable_alerts_alertprofile_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['switch_board__name', 'uuid']},
        ),
        migrations.AlterModelOptions(
            name='electricmeter',
            options={'ordering': ['channel__device__switch_board__name', 'channel__device__uuid', 'channel__channel_name', 'slave_id']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='switchboard',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='Przekroczenie', max_length=128)),
                ('datetime_from', models.DateTimeField()),
                ('datetime_to', models.DateTimeField(null=True)),
                ('confirmed_admin_operator', models.BooleanField(default=False)),
                ('confirmed_user', models.BooleanField(default=False)),
                ('alert_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.alertprofile')),
                ('energy_meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.electricmeter')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room')),
            ],
            options={
                'ordering': ['-datetime_from'],
            },
        ),
    ]
