# Generated by Django 5.2.8 on 2025-12-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_chat_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertprofile',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['device', 'channel_name']},
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-last_msg_date']},
        ),
        migrations.AlterModelOptions(
            name='roomgroup',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='alert',
            name='datetime_from',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_msg_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_edit_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
