# Generated by Django 5.2.8 on 2025-12-29 21:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_alertprofile_options_alter_channel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_seen_admin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_seen_operator',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_seen_user',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_msg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
