# Generated by Django 5.2.8 on 2025-12-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_chat_last_seen_admin_chat_last_seen_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_msg_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
