# Generated by Django 5.2.8 on 2025-12-29 21:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_chat_last_msg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_msg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
