# Generated by Django 5.2.8 on 2026-01-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_chat_last_msg_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='datetime_to',
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='l1_active_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='l1_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='l1_power_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='l1_reactive_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='l1_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='total_active_energy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='total_active_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='total_apparent_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='total_power_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='total_reactive_energy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='total_reactive_power',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
