# Generated by Django 5.2.8 on 2026-01-04 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_alert_datetime_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterreading',
            name='l1_power_factor',
        ),
        migrations.RemoveField(
            model_name='meterreading',
            name='l2_power_factor',
        ),
        migrations.RemoveField(
            model_name='meterreading',
            name='l3_power_factor',
        ),
    ]
